import './GameRepositoryConcurrency.testCases.js';
import './GameRepositoryCreateGame.testCases.js';
import './GameRepositoryLoadEvents.testCases.js';
import './GameRepositoryLobby.testCases.js';
import './GameRepositoryParticipants.testCases.js';
import './GameRepositoryPlayerProjections.testCases.js';
import './GameRepositorySaveCommand.testCases.js';
import './GameRepositorySystemEvents.testCases.js';
import './GameRepositoryWaitingGames.testCases.js';
