// This file is generated by tools/locale/generateLocaleResources.mjs.
// Do not edit it manually.

export interface WarChestResources {
  'app/router': {
    AppRouter: {
      loadingDescription: '';
      loadingLabel: '';
      loadingTitle: '';
      retry: '';
      sessionErrorDescription: '';
      sessionErrorTitle: '';
    };
  };
  'entities/game': {
    GameSeatSelector: {
      blackTeam: '';
      freeSeat: '';
      legend: '';
      seat: '';
      takenSeat: '';
      whiteTeam: '';
    };
  };
  'entities/user': {
    UserAvatar: {
      label: '{{userName}}';
    };
  };
  'features/auth-login': {
    GoogleLoginButton: {
      loadingLabel: '';
    };
    LoginOptions: {
      continueWithGoogle: '';
      continueWithTelegram: '';
      continueWithYandex: '';
      fakeModeHint: '';
      googleNotConfigured: '';
    };
  };
  'features/change-language': {
    LanguageSelector: {
      english: '';
      label: '';
      russian: '';
    };
  };
  'features/create-game': {
    CreateGameForm: {
      create: '';
      creating: '';
      description: '';
    };
  };
  'features/developer-tools': {
    DeveloperBackendSelector: {
      backend: '';
      fakeApi: '';
      realApi: '';
    };
    DeveloperPanel: {
      close: '';
      featureFlagDisabled: '';
      featureFlagEnabled: '';
      featureFlags: '';
      featureFlagsError: '';
      featureFlagsLoading: '';
      label: '';
      title: '';
    };
  };
  'features/join-game': {
    JoinGamePanel: {
      changeDescription: '';
      changePosition: '';
      changingPosition: '';
      join: '';
      joinDescription: '';
      joining: '';
      joinTitle: '';
    };
  };
  'features/start-game': {
    StartGameButton: {
      start: '';
      starting: '';
    };
  };
  'features/swap-player-positions': {
    SwapPlayerPositionsButton: {
      label: '';
    };
  };
  'pages/active-game': {
    ActiveGamePage: {
      actionsDescriptionOpponent: '';
      actionsDescriptionSpectator: '';
      actionsDescriptionYou: '';
      actionsTitle: '';
      backToLobby: '';
      boardDescription: '';
      boardLabel: '';
      chooseSquad: '';
      connecting: '';
      finishAction: '';
      finishedTitle: '';
      gameLabel: '{{gameId}}';
      gameTitle: '';
      gameUnavailable: '';
      historyDescription: '';
      historyEyebrow: '';
      historyTitle: '';
      notSelected: '';
      openHistory: '';
      opponent: '';
      playerBottom: '';
      playerTop: '';
      spectator: '';
      synchronization: {
        desynchronized: '';
        pending: '';
        ready: '';
      };
      table: '';
      tableArea: '';
      turnEyebrow: '';
      you: '';
    };
    GameError: {
      backToLobby: '';
      title: '';
    };
    PlayerPanel: {
      blackTeam: '';
      disconnected: '';
      empty: '';
      left: '';
      noPlayer: '';
      playerFallback: '{{playerId}}';
      whiteTeam: '';
    };
  };
  'pages/game': {
    GameError: {
      backToLobby: '';
      title: '';
    };
    GamePage: {
      backToLobby: '';
      blackTeam: '';
      connecting: '';
      creatorReadyNotice: '';
      gameLabel: '{{gameId}}';
      gameUnavailable: '';
      notSelected: '';
      ownGameDescription: '';
      ownGameTitle: '';
      returnToOwnGame: '';
      role: {
        creator: '';
        participant: '';
        select: '';
        spectator: '';
      };
      roleChoiceDescription: '';
      roleChoiceFullDescription: '';
      roleChoiceTitle: '';
      selectSeat: '';
      spectatorReadyNotice: '';
      spectatorWaitingNotice: '';
      status: {
        active: '';
        finished: '';
        waiting: '';
      };
      synchronization: {
        desynchronized: '';
        pending: '';
        ready: '';
      };
      watch: '';
      whiteTeam: '';
    };
    PlayerPosition: {
      available: '';
      connected: '';
      disconnected: '';
      left: '';
      playerFallback: '{{playerId}}';
      seat: '';
      you: '';
      youLabel: '{{playerName}}';
    };
  };
  'pages/game-history': {
    GameHistoryPage: {
      description: '{{gameId}}';
      missingGame: '';
      title: '';
    };
  };
  'pages/lobby': {
    GameCard: {
      blackTeam: '';
      openGame: '';
      statusActive: '';
      statusWaiting: '';
      whiteTeam: '';
    };
    LobbyPage: {
      activeGames: '';
      description: '';
      emptyDescription: '';
      emptyTitle: '';
      eyebrow: '';
      loading: '';
      newGame: '';
      retry: '';
      returnToGame: '';
      title: '';
    };
    TeamSlot: {
      available: '';
    };
  };
  'pages/login': {
    LoginPage: {
      connectionError: '';
      description: '';
      loadingDescription: '';
      loadingLabel: '';
      loadingTitle: '';
      retry: '';
      title: '';
    };
  };
  'pages/new-game': {
    NewGamePage: {
      description: '';
      title: '';
    };
  };
  'pages/user-profile': {
    UserProfilePage: {
      currentUserDescription: '';
      publicUserDescription: '{{userId}}';
      title: '';
    };
  };
  'shared/api': {
    ApiErrors: {
      avatar_not_found: '';
      command_id_conflict: '';
      external_provider_unavailable: '';
      feature_flags_unavailable: '';
      game_command_forbidden: '';
      game_command_rejected: '';
      game_not_found: '';
      game_position_occupied: '';
      game_version_conflict: '';
      internal_error: '';
      invalid_credentials: '';
      invalid_cursor: '';
      invalid_message: '';
      invalid_oauth_state: '';
      invalid_request: '';
      invalid_response: '';
      network_error: '';
      not_found: '';
      player_already_in_game: '';
      provider_disabled: '';
      provider_request_failed: '';
      unauthorized: '';
      unknown: '';
      user_not_found: '';
    };
  };
  'shared/ui': {
    PlaceholderPage: {
      homeLinkLabel: '';
    };
  };
  'widgets/session-navigation': {
    SessionNavigation: {
      devTools: '';
      lobby: '';
      loggingOutFallback: '';
      logout: '';
      mainNavigation: '';
      profile: '';
      sessionPending: '';
    };
  };
}

export interface WarChestTranslationParameters {
  'app/router.AppRouter.loadingDescription': null;
  'app/router.AppRouter.loadingLabel': null;
  'app/router.AppRouter.loadingTitle': null;
  'app/router.AppRouter.retry': null;
  'app/router.AppRouter.sessionErrorDescription': null;
  'app/router.AppRouter.sessionErrorTitle': null;
  'entities/game.GameSeatSelector.blackTeam': null;
  'entities/game.GameSeatSelector.freeSeat': null;
  'entities/game.GameSeatSelector.legend': null;
  'entities/game.GameSeatSelector.seat': null;
  'entities/game.GameSeatSelector.takenSeat': null;
  'entities/game.GameSeatSelector.whiteTeam': null;
  'entities/user.UserAvatar.label': { userName: unknown };
  'features/auth-login.GoogleLoginButton.loadingLabel': null;
  'features/auth-login.LoginOptions.continueWithGoogle': null;
  'features/auth-login.LoginOptions.continueWithTelegram': null;
  'features/auth-login.LoginOptions.continueWithYandex': null;
  'features/auth-login.LoginOptions.fakeModeHint': null;
  'features/auth-login.LoginOptions.googleNotConfigured': null;
  'features/change-language.LanguageSelector.english': null;
  'features/change-language.LanguageSelector.label': null;
  'features/change-language.LanguageSelector.russian': null;
  'features/create-game.CreateGameForm.create': null;
  'features/create-game.CreateGameForm.creating': null;
  'features/create-game.CreateGameForm.description': null;
  'features/developer-tools.DeveloperBackendSelector.backend': null;
  'features/developer-tools.DeveloperBackendSelector.fakeApi': null;
  'features/developer-tools.DeveloperBackendSelector.realApi': null;
  'features/developer-tools.DeveloperPanel.close': null;
  'features/developer-tools.DeveloperPanel.featureFlagDisabled': null;
  'features/developer-tools.DeveloperPanel.featureFlagEnabled': null;
  'features/developer-tools.DeveloperPanel.featureFlags': null;
  'features/developer-tools.DeveloperPanel.featureFlagsError': null;
  'features/developer-tools.DeveloperPanel.featureFlagsLoading': null;
  'features/developer-tools.DeveloperPanel.label': null;
  'features/developer-tools.DeveloperPanel.title': null;
  'features/join-game.JoinGamePanel.changeDescription': null;
  'features/join-game.JoinGamePanel.changePosition': null;
  'features/join-game.JoinGamePanel.changingPosition': null;
  'features/join-game.JoinGamePanel.join': null;
  'features/join-game.JoinGamePanel.joinDescription': null;
  'features/join-game.JoinGamePanel.joining': null;
  'features/join-game.JoinGamePanel.joinTitle': null;
  'features/start-game.StartGameButton.start': null;
  'features/start-game.StartGameButton.starting': null;
  'features/swap-player-positions.SwapPlayerPositionsButton.label': null;
  'pages/active-game.ActiveGamePage.actionsDescriptionOpponent': null;
  'pages/active-game.ActiveGamePage.actionsDescriptionSpectator': null;
  'pages/active-game.ActiveGamePage.actionsDescriptionYou': null;
  'pages/active-game.ActiveGamePage.actionsTitle': null;
  'pages/active-game.ActiveGamePage.backToLobby': null;
  'pages/active-game.ActiveGamePage.boardDescription': null;
  'pages/active-game.ActiveGamePage.boardLabel': null;
  'pages/active-game.ActiveGamePage.chooseSquad': null;
  'pages/active-game.ActiveGamePage.connecting': null;
  'pages/active-game.ActiveGamePage.finishAction': null;
  'pages/active-game.ActiveGamePage.finishedTitle': null;
  'pages/active-game.ActiveGamePage.gameLabel': { gameId: unknown };
  'pages/active-game.ActiveGamePage.gameTitle': null;
  'pages/active-game.ActiveGamePage.gameUnavailable': null;
  'pages/active-game.ActiveGamePage.historyDescription': null;
  'pages/active-game.ActiveGamePage.historyEyebrow': null;
  'pages/active-game.ActiveGamePage.historyTitle': null;
  'pages/active-game.ActiveGamePage.notSelected': null;
  'pages/active-game.ActiveGamePage.openHistory': null;
  'pages/active-game.ActiveGamePage.opponent': null;
  'pages/active-game.ActiveGamePage.playerBottom': null;
  'pages/active-game.ActiveGamePage.playerTop': null;
  'pages/active-game.ActiveGamePage.spectator': null;
  'pages/active-game.ActiveGamePage.synchronization.desynchronized': null;
  'pages/active-game.ActiveGamePage.synchronization.pending': null;
  'pages/active-game.ActiveGamePage.synchronization.ready': null;
  'pages/active-game.ActiveGamePage.table': null;
  'pages/active-game.ActiveGamePage.tableArea': null;
  'pages/active-game.ActiveGamePage.turnEyebrow': null;
  'pages/active-game.ActiveGamePage.you': null;
  'pages/active-game.GameError.backToLobby': null;
  'pages/active-game.GameError.title': null;
  'pages/active-game.PlayerPanel.blackTeam': null;
  'pages/active-game.PlayerPanel.disconnected': null;
  'pages/active-game.PlayerPanel.empty': null;
  'pages/active-game.PlayerPanel.left': null;
  'pages/active-game.PlayerPanel.noPlayer': null;
  'pages/active-game.PlayerPanel.playerFallback': { playerId: unknown };
  'pages/active-game.PlayerPanel.whiteTeam': null;
  'pages/game.GameError.backToLobby': null;
  'pages/game.GameError.title': null;
  'pages/game.GamePage.backToLobby': null;
  'pages/game.GamePage.blackTeam': null;
  'pages/game.GamePage.connecting': null;
  'pages/game.GamePage.creatorReadyNotice': null;
  'pages/game.GamePage.gameLabel': { gameId: unknown };
  'pages/game.GamePage.gameUnavailable': null;
  'pages/game.GamePage.notSelected': null;
  'pages/game.GamePage.ownGameDescription': null;
  'pages/game.GamePage.ownGameTitle': null;
  'pages/game.GamePage.returnToOwnGame': null;
  'pages/game.GamePage.role.creator': null;
  'pages/game.GamePage.role.participant': null;
  'pages/game.GamePage.role.select': null;
  'pages/game.GamePage.role.spectator': null;
  'pages/game.GamePage.roleChoiceDescription': null;
  'pages/game.GamePage.roleChoiceFullDescription': null;
  'pages/game.GamePage.roleChoiceTitle': null;
  'pages/game.GamePage.selectSeat': null;
  'pages/game.GamePage.spectatorReadyNotice': null;
  'pages/game.GamePage.spectatorWaitingNotice': null;
  'pages/game.GamePage.status.active': null;
  'pages/game.GamePage.status.finished': null;
  'pages/game.GamePage.status.waiting': null;
  'pages/game.GamePage.synchronization.desynchronized': null;
  'pages/game.GamePage.synchronization.pending': null;
  'pages/game.GamePage.synchronization.ready': null;
  'pages/game.GamePage.watch': null;
  'pages/game.GamePage.whiteTeam': null;
  'pages/game.PlayerPosition.available': null;
  'pages/game.PlayerPosition.connected': null;
  'pages/game.PlayerPosition.disconnected': null;
  'pages/game.PlayerPosition.left': null;
  'pages/game.PlayerPosition.playerFallback': { playerId: unknown };
  'pages/game.PlayerPosition.seat': null;
  'pages/game.PlayerPosition.you': null;
  'pages/game.PlayerPosition.youLabel': { playerName: unknown };
  'pages/game-history.GameHistoryPage.description': { gameId: unknown };
  'pages/game-history.GameHistoryPage.missingGame': null;
  'pages/game-history.GameHistoryPage.title': null;
  'pages/lobby.GameCard.blackTeam': null;
  'pages/lobby.GameCard.openGame': null;
  'pages/lobby.GameCard.statusActive': null;
  'pages/lobby.GameCard.statusWaiting': null;
  'pages/lobby.GameCard.whiteTeam': null;
  'pages/lobby.LobbyPage.activeGames': null;
  'pages/lobby.LobbyPage.description': null;
  'pages/lobby.LobbyPage.emptyDescription': null;
  'pages/lobby.LobbyPage.emptyTitle': null;
  'pages/lobby.LobbyPage.eyebrow': null;
  'pages/lobby.LobbyPage.loading': null;
  'pages/lobby.LobbyPage.newGame': null;
  'pages/lobby.LobbyPage.retry': null;
  'pages/lobby.LobbyPage.returnToGame': null;
  'pages/lobby.LobbyPage.title': null;
  'pages/lobby.TeamSlot.available': null;
  'pages/login.LoginPage.connectionError': null;
  'pages/login.LoginPage.description': null;
  'pages/login.LoginPage.loadingDescription': null;
  'pages/login.LoginPage.loadingLabel': null;
  'pages/login.LoginPage.loadingTitle': null;
  'pages/login.LoginPage.retry': null;
  'pages/login.LoginPage.title': null;
  'pages/new-game.NewGamePage.description': null;
  'pages/new-game.NewGamePage.title': null;
  'pages/user-profile.UserProfilePage.currentUserDescription': null;
  'pages/user-profile.UserProfilePage.publicUserDescription': {
    userId: unknown;
  };
  'pages/user-profile.UserProfilePage.title': null;
  'shared/api.ApiErrors.avatar_not_found': null;
  'shared/api.ApiErrors.command_id_conflict': null;
  'shared/api.ApiErrors.external_provider_unavailable': null;
  'shared/api.ApiErrors.feature_flags_unavailable': null;
  'shared/api.ApiErrors.game_command_forbidden': null;
  'shared/api.ApiErrors.game_command_rejected': null;
  'shared/api.ApiErrors.game_not_found': null;
  'shared/api.ApiErrors.game_position_occupied': null;
  'shared/api.ApiErrors.game_version_conflict': null;
  'shared/api.ApiErrors.internal_error': null;
  'shared/api.ApiErrors.invalid_credentials': null;
  'shared/api.ApiErrors.invalid_cursor': null;
  'shared/api.ApiErrors.invalid_message': null;
  'shared/api.ApiErrors.invalid_oauth_state': null;
  'shared/api.ApiErrors.invalid_request': null;
  'shared/api.ApiErrors.invalid_response': null;
  'shared/api.ApiErrors.network_error': null;
  'shared/api.ApiErrors.not_found': null;
  'shared/api.ApiErrors.player_already_in_game': null;
  'shared/api.ApiErrors.provider_disabled': null;
  'shared/api.ApiErrors.provider_request_failed': null;
  'shared/api.ApiErrors.unauthorized': null;
  'shared/api.ApiErrors.unknown': null;
  'shared/api.ApiErrors.user_not_found': null;
  'shared/ui.PlaceholderPage.homeLinkLabel': null;
  'widgets/session-navigation.SessionNavigation.devTools': null;
  'widgets/session-navigation.SessionNavigation.lobby': null;
  'widgets/session-navigation.SessionNavigation.loggingOutFallback': null;
  'widgets/session-navigation.SessionNavigation.logout': null;
  'widgets/session-navigation.SessionNavigation.mainNavigation': null;
  'widgets/session-navigation.SessionNavigation.profile': null;
  'widgets/session-navigation.SessionNavigation.sessionPending': null;
}

export type WarChestNamespace = keyof WarChestResources;
