// This file is generated by tools/locale/generateLocaleResources.mjs.
// Do not edit it manually.

export interface WarChestResources {
  'app/router': {
    AppRouter: {
      loadingDescription: '';
      loadingLabel: '';
      loadingTitle: '';
      retry: '';
      sessionErrorDescription: '';
      sessionErrorTitle: '';
    };
  };
  'entities/user': {
    UserAvatar: {
      label: '{{userName}}';
    };
    UserProfileLink: {
      label: '{{userName}}';
    };
  };
  'features/auth-login': {
    CodeStage: {
      changeEmail: '';
      checkingCode: '';
      codeDescription: '{{email}}';
      codeLabel: '';
      resendCode: '';
      resendCountdown: '{{seconds}}';
      signIn: '';
    };
    EmailLoginForm: {
      fakeModeHint: '';
    };
    EmailStage: {
      emailLabel: '';
      emailPlaceholder: '';
      sendCode: '';
      sendingCode: '';
    };
    RegistrationStage: {
      createProfile: '';
      creatingProfile: '';
      displayNameLabel: '';
      displayNameRequirements: '';
      registrationDescription: '';
    };
  };
  'features/change-language': {
    LanguageSelector: {
      english: '';
      label: '';
      russian: '';
    };
  };
  'features/complete-card-selection': {
    AutoCompleteCardSelection: {
      pending: '';
      retry: '';
    };
  };
  'features/confirm-card-choice': {
    ConfirmCardChoiceButton: {
      confirmBan: '';
      confirmPick: '';
      pending: '';
      selectBan: '';
      selectCard: '';
    };
  };
  'features/create-game': {
    CreateGameForm: {
      create: '';
      creating: '';
      description: '';
      format: {
        duel: {
          description: '';
          title: '';
        };
        legend: '';
        team: {
          description: '';
          title: '';
        };
      };
      select: '';
      selected: '';
    };
  };
  'features/developer-tools': {
    DeveloperBackendSelector: {
      backend: '';
      fakeApi: '';
      realApi: '';
    };
    DeveloperPanel: {
      close: '';
      featureFlagDisabled: '';
      featureFlagEnabled: '';
      featureFlags: '';
      featureFlagsError: '';
      featureFlagsLoading: '';
      label: '';
      title: '';
    };
  };
  'features/join-game': {
    JoinGameButton: {
      label: '{{seat}}';
    };
  };
  'features/leave-game': {
    LeaveGameButton: {
      close: '';
      closing: '';
      leave: '';
      leaving: '';
    };
  };
  'features/start-game': {
    StartGameButton: {
      start: '';
      starting: '';
    };
  };
  'features/surrender-game': {
    SurrenderGameButton: {
      surrender: '';
      surrendering: '';
    };
  };
  'features/swap-player-positions': {
    SwapPlayerPositionsButton: {
      label: '';
    };
  };
  'features/update-game-settings': {
    UpdateGameSettingsForm: {
      expansions: {
        description: '';
        nightfall: {
          description: '';
          title: '';
        };
        nobility: {
          description: '';
          title: '';
        };
        siege: {
          description: '';
          title: '';
        };
        title: '';
      };
      select: '';
      selected: '';
      selection: {
        description: '';
        draft: {
          description: '';
          title: '';
        };
        eliminationDraft: {
          description: '';
          title: '';
        };
        random: {
          description: '';
          title: '';
        };
        title: '';
      };
      unavailable: '';
    };
  };
  'pages/active-game': {
    ActiveGameHeader: {
      backToLobby: '';
      finishedTitle: '';
      gameLabel: '{{gameId}}';
      gameTitle: '';
      opponentSurrenderedTitle: '';
      spectator: '';
      spectatorWinnerTitle: '{{winner}}';
      surrenderedTitle: '';
      table: '';
      winnerFallback: '{{playerId}}';
    };
    ActiveGamePage: {
      connecting: '';
      gameUnavailable: '';
      notSelected: '';
      synchronization: {
        desynchronized: '';
        pending: '';
        ready: '';
      };
    };
    ActiveGameSidebar: {
      actionsDescriptionOpponent: '';
      actionsDescriptionSpectator: '';
      actionsDescriptionYou: '';
      actionsTitle: '';
      chooseSquad: '';
      finishAction: '';
      historyDescription: '';
      historyEyebrow: '';
      historyTitle: '';
      openHistory: '';
      turnEyebrow: '';
    };
    ActiveGameTable: {
      ally: '';
      opponent: '';
      playerBottom: '';
      playerFallback: '{{playerId}}';
      playerTop: '';
      preparing: '';
      showTeammate: '';
      tableArea: '';
      you: '';
    };
    BattlefieldBoard: {
      cell: '{{cellId}}';
      controlPoint: '{{cellId}}';
      initiative: '{{player}}';
      resetZoom: '';
      unit: '{{cellId}} {{unit}}';
      zoomControls: '';
      zoomIn: '';
      zoomOut: '';
    };
    CardSelectionPage: {
      actionHint: '';
      afterBansHint: '';
      automaticTransitionHint: '';
      available: '';
      banCount: '{{count}}';
      banned: '';
      blackTeam: '';
      candidate: '';
      candidateHint: '{{unit}}';
      candidateRepeatHint: '{{unit}}';
      compactCount: '{{count}} {{total}}';
      compactCurrentCount: '{{count}} {{total}}';
      count: '{{count}} {{total}}';
      currentCount: '{{count}} {{total}}';
      currentCountMobile: '{{count}} {{total}}';
      draftMode: '';
      duelBanDescription: '{{number}} {{total}}';
      duelDescription: '{{total}}';
      duelEliminationDescription: '';
      duelEliminationSequence: '';
      duelEyebrow: '{{mode}}';
      duelSequence: '';
      eliminationDraftMode: '';
      emptyCard: '';
      forwardHint: '';
      lastPick: '{{number}}';
      lastRoundHint: '';
      nextBan: '{{number}} {{player}}';
      nextForwardHint: '';
      nextPick: '{{number}} {{player}}';
      nextReverseHint: '';
      opponentBanTurn: '{{player}}';
      opponentPickTurn: '{{player}}';
      playerFallback: '{{playerId}}';
      reverseHint: '';
      selectedByAlly: '';
      selectedByOpponent: '';
      selectedByYou: '';
      selectedCards: '';
      teamBanDescription: '';
      teamBanHint: '';
      teamBanTurn: '{{number}} {{player}}';
      teamBanTurnMobile: '{{number}} {{player}}';
      teamDescription: '';
      teamEliminationDescription: '';
      teamEyebrow: '{{mode}}';
      teamForwardTurn: '{{number}} {{player}}';
      teamForwardTurnMobile: '{{number}} {{player}}';
      teamReverseTurn: '{{number}} {{player}}';
      teamReverseTurnMobile: '{{number}} {{player}}';
      title: '';
      units: {
        archer: '';
        berserker: '';
        cavalry: '';
        crossbowman: '';
        ensign: '';
        footman: '';
        knight: '';
        lancer: '';
        lightCavalry: '';
        marshal: '';
        mercenary: '';
        pikeman: '';
        royalGuard: '';
        scout: '';
        swordsman: '';
        warriorPriest: '';
      };
      waitHint: '';
      whiteTeam: '';
      you: '';
      yourBanTurn: '';
      yourPickTurn: '';
      youSuffix: '';
    };
    GameError: {
      backToLobby: '';
      title: '';
    };
    PlayerPanel: {
      bag: '';
      blackTeam: '';
      disconnected: '';
      eliminated: '';
      empty: '';
      hand: '{{count}}';
      initiative: '';
      left: '';
      noPlayer: '';
      playerFallback: '{{playerId}}';
      supply: '';
      unitCount: '{{count}} {{total}}';
      whiteTeam: '';
    };
  };
  'pages/game': {
    GameError: {
      backToLobby: '';
      title: '';
    };
    GamePage: {
      backToLobby: '';
      blackTeam: '';
      connecting: '';
      creatorReadyNotice: '';
      format: {
        duel: '';
        team: '';
      };
      gameLabel: '{{gameId}}';
      gameUnavailable: '';
      notSelected: '';
      ownGameDescription: '';
      ownGameTitle: '';
      returnToOwnGame: '';
      role: {
        creator: '';
        participant: '';
        select: '';
        spectator: '';
      };
      roleChoiceDescription: '';
      roleChoiceFullDescription: '';
      roleChoiceTitle: '';
      spectatorReadyNotice: '';
      spectatorWaitingNotice: '';
      status: {
        active: '';
        finished: '';
        waiting: '';
      };
      synchronization: {
        desynchronized: '';
        pending: '';
        ready: '';
      };
      watch: '';
      whiteTeam: '';
    };
    PlayerPosition: {
      available: '';
      connected: '{{seat}}';
      disconnected: '';
      left: '';
      playerFallback: '{{playerId}}';
      seat: '{{seat}}';
      you: '';
      youLabel: '{{playerName}}';
    };
  };
  'pages/game-history': {
    GameHistoryPage: {
      description: '{{gameId}}';
      missingGame: '';
      title: '';
    };
  };
  'pages/lobby': {
    GameCard: {
      blackTeam: '';
      configuration: '{{format}} {{selection}}';
      format: {
        duel: '';
        team: '';
      };
      openGame: '';
      selection: {
        draft: '';
        eliminationDraft: '';
        random: '';
      };
      statusActive: '';
      statusWaiting: '';
      whiteTeam: '';
    };
    LobbyPage: {
      activeGames: '';
      description: '';
      emptyDescription: '';
      emptyTitle: '';
      eyebrow: '';
      loading: '';
      newGame: '';
      retry: '';
      returnToGame: '';
      title: '';
    };
    TeamSlot: {
      available: '';
    };
  };
  'pages/login': {
    LoginPage: {
      connectionError: '';
      description: '';
      loadingDescription: '';
      loadingLabel: '';
      loadingTitle: '';
      retry: '';
      title: '';
    };
  };
  'pages/new-game': {
    NewGamePage: {
      description: '';
      title: '';
    };
  };
  'pages/user-game-history': {
    GameCard: {
      blackTeam: '';
      configuration: '{{format}} {{selection}}';
      defeat: '';
      format: {
        duel: '';
        team: '';
      };
      selection: {
        draft: '';
        eliminationDraft: '';
        random: '';
      };
      victory: '';
      viewGame: '';
      whiteTeam: '';
      yourTeam: '{{team}}';
    };
    HistoryError: {
      retry: '';
      title: '';
    };
    Team: {
      seat: '{{seat}}';
      winner: '';
    };
    UserGameHistoryPage: {
      backToProfile: '';
      description: '';
      emptyDescription: '';
      emptyTitle: '';
      eyebrow: '';
      gamesList: '';
      loadingHistory: '';
      loadingMore: '';
      loadingProfile: '';
      loadMore: '';
      missingUser: '';
      retry: '';
      title: '{{userName}}';
    };
  };
  'pages/user-profile': {
    HistorySection: {
      description: '';
      openHistory: '';
      title: '';
    };
    UserProfilePage: {
      avatarDescription: '';
      avatarRemoved: '';
      avatarSaved: '';
      avatarTitle: '';
      currentUserDescription: '';
      errorTitle: '';
      loadingProfile: '';
      nicknameLabel: '';
      nicknameRequirements: '';
      nicknameSaved: '';
      nicknameTitle: '';
      presets: {
        apricotCalm: '';
        blueGrin: '';
        butterJoy: '';
        clown: '';
        coralMischief: '';
        creamRound: '';
        lavenderSleepy: '';
        lilacFreckles: '';
        melonDreamy: '';
        mintWink: '';
        peachShy: '';
        periwinkleLaugh: '';
        pinkSmile: '';
        roseTuft: '';
        skyCurious: '';
        turquoiseSurprise: '';
      };
      publicProfile: '';
      publicUserDescription: '';
      removeAvatar: '';
      retry: '';
      saveNickname: '';
      title: '';
      uploadAvatar: '';
    };
  };
  'shared/api': {
    ApiErrors: {
      avatar_invalid: '';
      avatar_not_found: '';
      avatar_too_large: '';
      command_id_conflict: '';
      email_code_invalid: '';
      email_code_rate_limited: '';
      email_delivery_unavailable: '';
      feature_flags_unavailable: '';
      game_command_forbidden: '';
      game_command_rejected: '';
      game_not_found: '';
      game_position_occupied: '';
      game_version_conflict: '';
      internal_error: '';
      invalid_cursor: '';
      invalid_message: '';
      invalid_request: '';
      invalid_response: '';
      network_error: '';
      not_found: '';
      player_already_in_game: '';
      registration_ticket_invalid: '';
      unauthorized: '';
      unknown: '';
      user_not_found: '';
    };
  };
  'shared/ui': {
    PlaceholderPage: {
      homeLinkLabel: '';
    };
  };
  'widgets/session-navigation': {
    SessionNavigation: {
      devTools: '';
      lobby: '';
      loggingOutFallback: '';
      logout: '';
      mainNavigation: '';
      profile: '';
      sessionPending: '';
    };
  };
}

export interface WarChestTranslationParameters {
  'app/router.AppRouter.loadingDescription': null;
  'app/router.AppRouter.loadingLabel': null;
  'app/router.AppRouter.loadingTitle': null;
  'app/router.AppRouter.retry': null;
  'app/router.AppRouter.sessionErrorDescription': null;
  'app/router.AppRouter.sessionErrorTitle': null;
  'entities/user.UserAvatar.label': { userName: unknown };
  'entities/user.UserProfileLink.label': { userName: unknown };
  'features/auth-login.CodeStage.changeEmail': null;
  'features/auth-login.CodeStage.checkingCode': null;
  'features/auth-login.CodeStage.codeDescription': { email: unknown };
  'features/auth-login.CodeStage.codeLabel': null;
  'features/auth-login.CodeStage.resendCode': null;
  'features/auth-login.CodeStage.resendCountdown': { seconds: unknown };
  'features/auth-login.CodeStage.signIn': null;
  'features/auth-login.EmailLoginForm.fakeModeHint': null;
  'features/auth-login.EmailStage.emailLabel': null;
  'features/auth-login.EmailStage.emailPlaceholder': null;
  'features/auth-login.EmailStage.sendCode': null;
  'features/auth-login.EmailStage.sendingCode': null;
  'features/auth-login.RegistrationStage.createProfile': null;
  'features/auth-login.RegistrationStage.creatingProfile': null;
  'features/auth-login.RegistrationStage.displayNameLabel': null;
  'features/auth-login.RegistrationStage.displayNameRequirements': null;
  'features/auth-login.RegistrationStage.registrationDescription': null;
  'features/change-language.LanguageSelector.english': null;
  'features/change-language.LanguageSelector.label': null;
  'features/change-language.LanguageSelector.russian': null;
  'features/complete-card-selection.AutoCompleteCardSelection.pending': null;
  'features/complete-card-selection.AutoCompleteCardSelection.retry': null;
  'features/confirm-card-choice.ConfirmCardChoiceButton.confirmBan': null;
  'features/confirm-card-choice.ConfirmCardChoiceButton.confirmPick': null;
  'features/confirm-card-choice.ConfirmCardChoiceButton.pending': null;
  'features/confirm-card-choice.ConfirmCardChoiceButton.selectBan': null;
  'features/confirm-card-choice.ConfirmCardChoiceButton.selectCard': null;
  'features/create-game.CreateGameForm.create': null;
  'features/create-game.CreateGameForm.creating': null;
  'features/create-game.CreateGameForm.description': null;
  'features/create-game.CreateGameForm.format.duel.description': null;
  'features/create-game.CreateGameForm.format.duel.title': null;
  'features/create-game.CreateGameForm.format.legend': null;
  'features/create-game.CreateGameForm.format.team.description': null;
  'features/create-game.CreateGameForm.format.team.title': null;
  'features/create-game.CreateGameForm.select': null;
  'features/create-game.CreateGameForm.selected': null;
  'features/developer-tools.DeveloperBackendSelector.backend': null;
  'features/developer-tools.DeveloperBackendSelector.fakeApi': null;
  'features/developer-tools.DeveloperBackendSelector.realApi': null;
  'features/developer-tools.DeveloperPanel.close': null;
  'features/developer-tools.DeveloperPanel.featureFlagDisabled': null;
  'features/developer-tools.DeveloperPanel.featureFlagEnabled': null;
  'features/developer-tools.DeveloperPanel.featureFlags': null;
  'features/developer-tools.DeveloperPanel.featureFlagsError': null;
  'features/developer-tools.DeveloperPanel.featureFlagsLoading': null;
  'features/developer-tools.DeveloperPanel.label': null;
  'features/developer-tools.DeveloperPanel.title': null;
  'features/join-game.JoinGameButton.label': { seat: unknown };
  'features/leave-game.LeaveGameButton.close': null;
  'features/leave-game.LeaveGameButton.closing': null;
  'features/leave-game.LeaveGameButton.leave': null;
  'features/leave-game.LeaveGameButton.leaving': null;
  'features/start-game.StartGameButton.start': null;
  'features/start-game.StartGameButton.starting': null;
  'features/surrender-game.SurrenderGameButton.surrender': null;
  'features/surrender-game.SurrenderGameButton.surrendering': null;
  'features/swap-player-positions.SwapPlayerPositionsButton.label': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.nightfall.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.nightfall.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.nobility.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.nobility.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.siege.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.siege.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.expansions.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.select': null;
  'features/update-game-settings.UpdateGameSettingsForm.selected': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.draft.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.draft.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.eliminationDraft.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.eliminationDraft.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.random.description': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.random.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.selection.title': null;
  'features/update-game-settings.UpdateGameSettingsForm.unavailable': null;
  'pages/active-game.ActiveGameHeader.backToLobby': null;
  'pages/active-game.ActiveGameHeader.finishedTitle': null;
  'pages/active-game.ActiveGameHeader.gameLabel': { gameId: unknown };
  'pages/active-game.ActiveGameHeader.gameTitle': null;
  'pages/active-game.ActiveGameHeader.opponentSurrenderedTitle': null;
  'pages/active-game.ActiveGameHeader.spectator': null;
  'pages/active-game.ActiveGameHeader.spectatorWinnerTitle': {
    winner: unknown;
  };
  'pages/active-game.ActiveGameHeader.surrenderedTitle': null;
  'pages/active-game.ActiveGameHeader.table': null;
  'pages/active-game.ActiveGameHeader.winnerFallback': { playerId: unknown };
  'pages/active-game.ActiveGamePage.connecting': null;
  'pages/active-game.ActiveGamePage.gameUnavailable': null;
  'pages/active-game.ActiveGamePage.notSelected': null;
  'pages/active-game.ActiveGamePage.synchronization.desynchronized': null;
  'pages/active-game.ActiveGamePage.synchronization.pending': null;
  'pages/active-game.ActiveGamePage.synchronization.ready': null;
  'pages/active-game.ActiveGameSidebar.actionsDescriptionOpponent': null;
  'pages/active-game.ActiveGameSidebar.actionsDescriptionSpectator': null;
  'pages/active-game.ActiveGameSidebar.actionsDescriptionYou': null;
  'pages/active-game.ActiveGameSidebar.actionsTitle': null;
  'pages/active-game.ActiveGameSidebar.chooseSquad': null;
  'pages/active-game.ActiveGameSidebar.finishAction': null;
  'pages/active-game.ActiveGameSidebar.historyDescription': null;
  'pages/active-game.ActiveGameSidebar.historyEyebrow': null;
  'pages/active-game.ActiveGameSidebar.historyTitle': null;
  'pages/active-game.ActiveGameSidebar.openHistory': null;
  'pages/active-game.ActiveGameSidebar.turnEyebrow': null;
  'pages/active-game.ActiveGameTable.ally': null;
  'pages/active-game.ActiveGameTable.opponent': null;
  'pages/active-game.ActiveGameTable.playerBottom': null;
  'pages/active-game.ActiveGameTable.playerFallback': { playerId: unknown };
  'pages/active-game.ActiveGameTable.playerTop': null;
  'pages/active-game.ActiveGameTable.preparing': null;
  'pages/active-game.ActiveGameTable.showTeammate': null;
  'pages/active-game.ActiveGameTable.tableArea': null;
  'pages/active-game.ActiveGameTable.you': null;
  'pages/active-game.BattlefieldBoard.cell': { cellId: unknown };
  'pages/active-game.BattlefieldBoard.controlPoint': { cellId: unknown };
  'pages/active-game.BattlefieldBoard.initiative': { player: unknown };
  'pages/active-game.BattlefieldBoard.resetZoom': null;
  'pages/active-game.BattlefieldBoard.unit': { cellId: unknown; unit: unknown };
  'pages/active-game.BattlefieldBoard.zoomControls': null;
  'pages/active-game.BattlefieldBoard.zoomIn': null;
  'pages/active-game.BattlefieldBoard.zoomOut': null;
  'pages/active-game.CardSelectionPage.actionHint': null;
  'pages/active-game.CardSelectionPage.afterBansHint': null;
  'pages/active-game.CardSelectionPage.automaticTransitionHint': null;
  'pages/active-game.CardSelectionPage.available': null;
  'pages/active-game.CardSelectionPage.banCount': { count: unknown };
  'pages/active-game.CardSelectionPage.banned': null;
  'pages/active-game.CardSelectionPage.blackTeam': null;
  'pages/active-game.CardSelectionPage.candidate': null;
  'pages/active-game.CardSelectionPage.candidateHint': { unit: unknown };
  'pages/active-game.CardSelectionPage.candidateRepeatHint': { unit: unknown };
  'pages/active-game.CardSelectionPage.compactCount': {
    count: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.compactCurrentCount': {
    count: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.count': {
    count: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.currentCount': {
    count: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.currentCountMobile': {
    count: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.draftMode': null;
  'pages/active-game.CardSelectionPage.duelBanDescription': {
    number: unknown;
    total: unknown;
  };
  'pages/active-game.CardSelectionPage.duelDescription': { total: unknown };
  'pages/active-game.CardSelectionPage.duelEliminationDescription': null;
  'pages/active-game.CardSelectionPage.duelEliminationSequence': null;
  'pages/active-game.CardSelectionPage.duelEyebrow': { mode: unknown };
  'pages/active-game.CardSelectionPage.duelSequence': null;
  'pages/active-game.CardSelectionPage.eliminationDraftMode': null;
  'pages/active-game.CardSelectionPage.emptyCard': null;
  'pages/active-game.CardSelectionPage.forwardHint': null;
  'pages/active-game.CardSelectionPage.lastPick': { number: unknown };
  'pages/active-game.CardSelectionPage.lastRoundHint': null;
  'pages/active-game.CardSelectionPage.nextBan': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.nextForwardHint': null;
  'pages/active-game.CardSelectionPage.nextPick': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.nextReverseHint': null;
  'pages/active-game.CardSelectionPage.opponentBanTurn': { player: unknown };
  'pages/active-game.CardSelectionPage.opponentPickTurn': { player: unknown };
  'pages/active-game.CardSelectionPage.playerFallback': { playerId: unknown };
  'pages/active-game.CardSelectionPage.reverseHint': null;
  'pages/active-game.CardSelectionPage.selectedByAlly': null;
  'pages/active-game.CardSelectionPage.selectedByOpponent': null;
  'pages/active-game.CardSelectionPage.selectedByYou': null;
  'pages/active-game.CardSelectionPage.selectedCards': null;
  'pages/active-game.CardSelectionPage.teamBanDescription': null;
  'pages/active-game.CardSelectionPage.teamBanHint': null;
  'pages/active-game.CardSelectionPage.teamBanTurn': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.teamBanTurnMobile': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.teamDescription': null;
  'pages/active-game.CardSelectionPage.teamEliminationDescription': null;
  'pages/active-game.CardSelectionPage.teamEyebrow': { mode: unknown };
  'pages/active-game.CardSelectionPage.teamForwardTurn': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.teamForwardTurnMobile': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.teamReverseTurn': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.teamReverseTurnMobile': {
    number: unknown;
    player: unknown;
  };
  'pages/active-game.CardSelectionPage.title': null;
  'pages/active-game.CardSelectionPage.units.archer': null;
  'pages/active-game.CardSelectionPage.units.berserker': null;
  'pages/active-game.CardSelectionPage.units.cavalry': null;
  'pages/active-game.CardSelectionPage.units.crossbowman': null;
  'pages/active-game.CardSelectionPage.units.ensign': null;
  'pages/active-game.CardSelectionPage.units.footman': null;
  'pages/active-game.CardSelectionPage.units.knight': null;
  'pages/active-game.CardSelectionPage.units.lancer': null;
  'pages/active-game.CardSelectionPage.units.lightCavalry': null;
  'pages/active-game.CardSelectionPage.units.marshal': null;
  'pages/active-game.CardSelectionPage.units.mercenary': null;
  'pages/active-game.CardSelectionPage.units.pikeman': null;
  'pages/active-game.CardSelectionPage.units.royalGuard': null;
  'pages/active-game.CardSelectionPage.units.scout': null;
  'pages/active-game.CardSelectionPage.units.swordsman': null;
  'pages/active-game.CardSelectionPage.units.warriorPriest': null;
  'pages/active-game.CardSelectionPage.waitHint': null;
  'pages/active-game.CardSelectionPage.whiteTeam': null;
  'pages/active-game.CardSelectionPage.you': null;
  'pages/active-game.CardSelectionPage.yourBanTurn': null;
  'pages/active-game.CardSelectionPage.yourPickTurn': null;
  'pages/active-game.CardSelectionPage.youSuffix': null;
  'pages/active-game.GameError.backToLobby': null;
  'pages/active-game.GameError.title': null;
  'pages/active-game.PlayerPanel.bag': null;
  'pages/active-game.PlayerPanel.blackTeam': null;
  'pages/active-game.PlayerPanel.disconnected': null;
  'pages/active-game.PlayerPanel.eliminated': null;
  'pages/active-game.PlayerPanel.empty': null;
  'pages/active-game.PlayerPanel.hand': { count: unknown };
  'pages/active-game.PlayerPanel.initiative': null;
  'pages/active-game.PlayerPanel.left': null;
  'pages/active-game.PlayerPanel.noPlayer': null;
  'pages/active-game.PlayerPanel.playerFallback': { playerId: unknown };
  'pages/active-game.PlayerPanel.supply': null;
  'pages/active-game.PlayerPanel.unitCount': { count: unknown; total: unknown };
  'pages/active-game.PlayerPanel.whiteTeam': null;
  'pages/game.GameError.backToLobby': null;
  'pages/game.GameError.title': null;
  'pages/game.GamePage.backToLobby': null;
  'pages/game.GamePage.blackTeam': null;
  'pages/game.GamePage.connecting': null;
  'pages/game.GamePage.creatorReadyNotice': null;
  'pages/game.GamePage.format.duel': null;
  'pages/game.GamePage.format.team': null;
  'pages/game.GamePage.gameLabel': { gameId: unknown };
  'pages/game.GamePage.gameUnavailable': null;
  'pages/game.GamePage.notSelected': null;
  'pages/game.GamePage.ownGameDescription': null;
  'pages/game.GamePage.ownGameTitle': null;
  'pages/game.GamePage.returnToOwnGame': null;
  'pages/game.GamePage.role.creator': null;
  'pages/game.GamePage.role.participant': null;
  'pages/game.GamePage.role.select': null;
  'pages/game.GamePage.role.spectator': null;
  'pages/game.GamePage.roleChoiceDescription': null;
  'pages/game.GamePage.roleChoiceFullDescription': null;
  'pages/game.GamePage.roleChoiceTitle': null;
  'pages/game.GamePage.spectatorReadyNotice': null;
  'pages/game.GamePage.spectatorWaitingNotice': null;
  'pages/game.GamePage.status.active': null;
  'pages/game.GamePage.status.finished': null;
  'pages/game.GamePage.status.waiting': null;
  'pages/game.GamePage.synchronization.desynchronized': null;
  'pages/game.GamePage.synchronization.pending': null;
  'pages/game.GamePage.synchronization.ready': null;
  'pages/game.GamePage.watch': null;
  'pages/game.GamePage.whiteTeam': null;
  'pages/game.PlayerPosition.available': null;
  'pages/game.PlayerPosition.connected': { seat: unknown };
  'pages/game.PlayerPosition.disconnected': null;
  'pages/game.PlayerPosition.left': null;
  'pages/game.PlayerPosition.playerFallback': { playerId: unknown };
  'pages/game.PlayerPosition.seat': { seat: unknown };
  'pages/game.PlayerPosition.you': null;
  'pages/game.PlayerPosition.youLabel': { playerName: unknown };
  'pages/game-history.GameHistoryPage.description': { gameId: unknown };
  'pages/game-history.GameHistoryPage.missingGame': null;
  'pages/game-history.GameHistoryPage.title': null;
  'pages/lobby.GameCard.blackTeam': null;
  'pages/lobby.GameCard.configuration': { format: unknown; selection: unknown };
  'pages/lobby.GameCard.format.duel': null;
  'pages/lobby.GameCard.format.team': null;
  'pages/lobby.GameCard.openGame': null;
  'pages/lobby.GameCard.selection.draft': null;
  'pages/lobby.GameCard.selection.eliminationDraft': null;
  'pages/lobby.GameCard.selection.random': null;
  'pages/lobby.GameCard.statusActive': null;
  'pages/lobby.GameCard.statusWaiting': null;
  'pages/lobby.GameCard.whiteTeam': null;
  'pages/lobby.LobbyPage.activeGames': null;
  'pages/lobby.LobbyPage.description': null;
  'pages/lobby.LobbyPage.emptyDescription': null;
  'pages/lobby.LobbyPage.emptyTitle': null;
  'pages/lobby.LobbyPage.eyebrow': null;
  'pages/lobby.LobbyPage.loading': null;
  'pages/lobby.LobbyPage.newGame': null;
  'pages/lobby.LobbyPage.retry': null;
  'pages/lobby.LobbyPage.returnToGame': null;
  'pages/lobby.LobbyPage.title': null;
  'pages/lobby.TeamSlot.available': null;
  'pages/login.LoginPage.connectionError': null;
  'pages/login.LoginPage.description': null;
  'pages/login.LoginPage.loadingDescription': null;
  'pages/login.LoginPage.loadingLabel': null;
  'pages/login.LoginPage.loadingTitle': null;
  'pages/login.LoginPage.retry': null;
  'pages/login.LoginPage.title': null;
  'pages/new-game.NewGamePage.description': null;
  'pages/new-game.NewGamePage.title': null;
  'pages/user-game-history.GameCard.blackTeam': null;
  'pages/user-game-history.GameCard.configuration': {
    format: unknown;
    selection: unknown;
  };
  'pages/user-game-history.GameCard.defeat': null;
  'pages/user-game-history.GameCard.format.duel': null;
  'pages/user-game-history.GameCard.format.team': null;
  'pages/user-game-history.GameCard.selection.draft': null;
  'pages/user-game-history.GameCard.selection.eliminationDraft': null;
  'pages/user-game-history.GameCard.selection.random': null;
  'pages/user-game-history.GameCard.victory': null;
  'pages/user-game-history.GameCard.viewGame': null;
  'pages/user-game-history.GameCard.whiteTeam': null;
  'pages/user-game-history.GameCard.yourTeam': { team: unknown };
  'pages/user-game-history.HistoryError.retry': null;
  'pages/user-game-history.HistoryError.title': null;
  'pages/user-game-history.Team.seat': { seat: unknown };
  'pages/user-game-history.Team.winner': null;
  'pages/user-game-history.UserGameHistoryPage.backToProfile': null;
  'pages/user-game-history.UserGameHistoryPage.description': null;
  'pages/user-game-history.UserGameHistoryPage.emptyDescription': null;
  'pages/user-game-history.UserGameHistoryPage.emptyTitle': null;
  'pages/user-game-history.UserGameHistoryPage.eyebrow': null;
  'pages/user-game-history.UserGameHistoryPage.gamesList': null;
  'pages/user-game-history.UserGameHistoryPage.loadingHistory': null;
  'pages/user-game-history.UserGameHistoryPage.loadingMore': null;
  'pages/user-game-history.UserGameHistoryPage.loadingProfile': null;
  'pages/user-game-history.UserGameHistoryPage.loadMore': null;
  'pages/user-game-history.UserGameHistoryPage.missingUser': null;
  'pages/user-game-history.UserGameHistoryPage.retry': null;
  'pages/user-game-history.UserGameHistoryPage.title': { userName: unknown };
  'pages/user-profile.HistorySection.description': null;
  'pages/user-profile.HistorySection.openHistory': null;
  'pages/user-profile.HistorySection.title': null;
  'pages/user-profile.UserProfilePage.avatarDescription': null;
  'pages/user-profile.UserProfilePage.avatarRemoved': null;
  'pages/user-profile.UserProfilePage.avatarSaved': null;
  'pages/user-profile.UserProfilePage.avatarTitle': null;
  'pages/user-profile.UserProfilePage.currentUserDescription': null;
  'pages/user-profile.UserProfilePage.errorTitle': null;
  'pages/user-profile.UserProfilePage.loadingProfile': null;
  'pages/user-profile.UserProfilePage.nicknameLabel': null;
  'pages/user-profile.UserProfilePage.nicknameRequirements': null;
  'pages/user-profile.UserProfilePage.nicknameSaved': null;
  'pages/user-profile.UserProfilePage.nicknameTitle': null;
  'pages/user-profile.UserProfilePage.presets.apricotCalm': null;
  'pages/user-profile.UserProfilePage.presets.blueGrin': null;
  'pages/user-profile.UserProfilePage.presets.butterJoy': null;
  'pages/user-profile.UserProfilePage.presets.clown': null;
  'pages/user-profile.UserProfilePage.presets.coralMischief': null;
  'pages/user-profile.UserProfilePage.presets.creamRound': null;
  'pages/user-profile.UserProfilePage.presets.lavenderSleepy': null;
  'pages/user-profile.UserProfilePage.presets.lilacFreckles': null;
  'pages/user-profile.UserProfilePage.presets.melonDreamy': null;
  'pages/user-profile.UserProfilePage.presets.mintWink': null;
  'pages/user-profile.UserProfilePage.presets.peachShy': null;
  'pages/user-profile.UserProfilePage.presets.periwinkleLaugh': null;
  'pages/user-profile.UserProfilePage.presets.pinkSmile': null;
  'pages/user-profile.UserProfilePage.presets.roseTuft': null;
  'pages/user-profile.UserProfilePage.presets.skyCurious': null;
  'pages/user-profile.UserProfilePage.presets.turquoiseSurprise': null;
  'pages/user-profile.UserProfilePage.publicProfile': null;
  'pages/user-profile.UserProfilePage.publicUserDescription': null;
  'pages/user-profile.UserProfilePage.removeAvatar': null;
  'pages/user-profile.UserProfilePage.retry': null;
  'pages/user-profile.UserProfilePage.saveNickname': null;
  'pages/user-profile.UserProfilePage.title': null;
  'pages/user-profile.UserProfilePage.uploadAvatar': null;
  'shared/api.ApiErrors.avatar_invalid': null;
  'shared/api.ApiErrors.avatar_not_found': null;
  'shared/api.ApiErrors.avatar_too_large': null;
  'shared/api.ApiErrors.command_id_conflict': null;
  'shared/api.ApiErrors.email_code_invalid': null;
  'shared/api.ApiErrors.email_code_rate_limited': null;
  'shared/api.ApiErrors.email_delivery_unavailable': null;
  'shared/api.ApiErrors.feature_flags_unavailable': null;
  'shared/api.ApiErrors.game_command_forbidden': null;
  'shared/api.ApiErrors.game_command_rejected': null;
  'shared/api.ApiErrors.game_not_found': null;
  'shared/api.ApiErrors.game_position_occupied': null;
  'shared/api.ApiErrors.game_version_conflict': null;
  'shared/api.ApiErrors.internal_error': null;
  'shared/api.ApiErrors.invalid_cursor': null;
  'shared/api.ApiErrors.invalid_message': null;
  'shared/api.ApiErrors.invalid_request': null;
  'shared/api.ApiErrors.invalid_response': null;
  'shared/api.ApiErrors.network_error': null;
  'shared/api.ApiErrors.not_found': null;
  'shared/api.ApiErrors.player_already_in_game': null;
  'shared/api.ApiErrors.registration_ticket_invalid': null;
  'shared/api.ApiErrors.unauthorized': null;
  'shared/api.ApiErrors.unknown': null;
  'shared/api.ApiErrors.user_not_found': null;
  'shared/ui.PlaceholderPage.homeLinkLabel': null;
  'widgets/session-navigation.SessionNavigation.devTools': null;
  'widgets/session-navigation.SessionNavigation.lobby': null;
  'widgets/session-navigation.SessionNavigation.loggingOutFallback': null;
  'widgets/session-navigation.SessionNavigation.logout': null;
  'widgets/session-navigation.SessionNavigation.mainNavigation': null;
  'widgets/session-navigation.SessionNavigation.profile': null;
  'widgets/session-navigation.SessionNavigation.sessionPending': null;
}

export type WarChestNamespace = keyof WarChestResources;
